---
# tasks file for asa_noturna
- name: role para DEPLOY
  hosts: all
  vars:
    - texto: "Testee pra ver quem lê"
  tasks:
    - include: prereqDebian.yml
    - include: prereqRedhat.yml
    - include: install_nginx.yml
    - include: deploy.yml
    

 

