- name: Para o Apache - DEBIAN
  service: 
    name: apache2
    state: stopped
  ignore_errors: True
  when: ansible_os_family == "Debian"

- name: Removendo Apache - DEBIAN
  apt: 
    name: apache2*
    state: absent
  when: ansible_os_family == "Debian"
