---
#PARAR NGINX
- name: Desafio
  hosts: all
  tasks:
    - name: Parar NGINX
      service:
        name: nginx*
        state: stopped
      ignore_errors: True
#REMOVE NGINX DO UBUNTU
    - name: Removendo NGINX - UBUNTU
      apt:
        name: nginx*
        state: absent
      when: ansible_distribution == "Ubuntu"
#REMOVE NGINX DO CENTOS
    - name: Removendo NGINX - CentOS
      yum: 
        name: nginx*
        state: absent
      when: ansible_distribution == "CentOS"
#INSTALA APACHE UBUNTU
    - name: Instalando Servidor Web - Ubuntu
      apt:
        name: ['apache2','libapache2-mod-php7.0','php7.0']
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
#INSTALA APACHE CENTOS
    - name: Instalando Servidor Web - CentOS
      yum: 
        name: ['httpd','php']
      notify: httpd
      when: ansible_distribution == "CentOS"
#INSTALA APACHE - UBUNTU
    - name: Ativando Modulo PHP - Ubuntu
      command: a2enmod php7.0
      when: ansible_distribution == "Ubuntu"
      

#COPIA INDEX
    - name: Copiando index.php
      copy: 
        src: /etc/ansible/index.php
        dest: /var/www/html/index.php

#GERENCIANDO SERVICOS
  handlers:
    - name: httpd
      service: 
        name: httpd
        state: restarted

    - name: apache
      service:
        name: apache2
        state: restarted 
