---
- name: Instalando Rundeck
  hosts: automation
  tasks:
  - name: Add Repositorio Rundeck
    yum:
      name: http://repo.rundeck.org/latest.rpm
      state: present
    register:

  - name: Mostrando Resultado
    debug:
      var: result.stdout 

    - name: Instalando Rundeck
      yum:
        name: ['java-1.8.0','rundeck']
	state: present 
